### ISSUE TITLE
Cannot play Video First time in IOS . Ver.2.2.4

### ISSUE THREAD

**Issue by Zachzx0** [RenderHeads/UnityPlugin-AVProVideo#1028]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 Unity version: 2020.3
AVPro Video version (number and edition (trial/core/ultra/enterprise)): core Edition 2.2.4
Operating system version: IOS,15.0.2 (19A404)
Device model: iPhone 11
Video specs (resolution, frame-rate, codec, file size):

My sdk wa upgraded to 2.2.4 from 2.1.8 . it resolved https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1000#issue-1046699765

but i cannot play my video when i play this video in the _first time_ . Just happend in ios.
Here is my code snippet.

![image](https://user-images.githubusercontent.com/41116914/143246798-64056cc4-bf7a-4b98-8386-e3dddd433a82.png)

![image](https://user-images.githubusercontent.com/41116914/143246821-5a7a5ba4-475b-475e-a643-54984dc96490.png)

![image](https://user-images.githubusercontent.com/41116914/143246844-d598af41-84c7-4c85-8daf-1f2a22e24f7e.png)
![image](https://user-images.githubusercontent.com/41116914/143246887-fa5db12a-58e7-4cac-9c0e-c195623a8622.png)

And here is my TestLog. It seems like that was already Load video successfully.but not play.
------------------------------------------LOG--------------------------------------------------------------
AVProTest切换视频！！！！！！！！！！！！！！！！！
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Test:ChangeVideo()
UnityEngine.Events.UnityAction:Invoke()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[AVProVideo] Opening /var/containers/Bundle/Application/E2CE6215-6163-4C86-85D5-CFBEBF744957/Avpro224Test.app/Data/Raw/AVProVideoSamples/BigBuckBunny-360p30-H264.mp4 (offset 0) with API 
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(Boolean)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(MediaPathType, String, Boolean, TransparencyMode)
RenderHeads.Media.AVProVideo.PlaylistMediaPlayer:OpenVideoFile(MediaItem)
RenderHeads.Media.AVProVideo.PlaylistMediaPlayer:JumpToItem(Int32)
NBAPlaylistVideo:Play(Boolean, NBAVideoConfig[])
Test:ChangeVideo()
UnityEngine.Events.UnityAction:Invoke()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

2021-11-24 21:13:10.436310+0800 Avpro224Test[1766:481064] [Player] asset duration is   7.97 seconds
2021-11-24 21:13:10.436659+0800 Avpro224Test[1766:481064] [Player] creating 3 player items
2021-11-24 21:13:10.447337+0800 Avpro224Test[1766:481064] [Player] asset has metadata
2021-11-24 21:13:10.448013+0800 Avpro224Test[1766:481064] [Player] asset is compatible with AirPlay
2021-11-24 21:13:10.449149+0800 Avpro224Test[1766:481064] [Player] asset has 1 audio tracks
2021-11-24 21:13:10.449228+0800 Avpro224Test[1766:481064] [Player] preparing audio capture...
2021-11-24 21:13:10.450633+0800 Avpro224Test[1766:481064] [Player]   max channel count is 2
2021-11-24 21:13:10.450682+0800 Avpro224Test[1766:481064] [Player]   capture buffer capacity is 144000
2021-11-24 21:13:10.451618+0800 Avpro224Test[1766:481064] [Player]   done
2021-11-24 21:13:10.471732+0800 Avpro224Test[1766:481064] [Player] player status is ready to play
2021-11-24 21:13:10.521928+0800 Avpro224Test[1766:481085] [AudioCapture] audio requires resampling from 48000Hz to 24000Hz, audio output may stutter
2021-11-24 21:13:10.547549+0800 Avpro224Test[1766:481064] [Player] player item status is ready to play
2021-11-24 21:13:10.577258+0800 Avpro224Test[1766:481064] [Player] player rate changed to 1.000000
2021-11-24 21:13:10.628440+0800 Avpro224Test[1766:481064] [Player] player item status is ready to play

**Comment by kahnivore** [comment]
What do you mean you can't play the video the 'first time'? 

Could you give us the specs of your video? 

Does it play in the Demo_MediaPlayer scene on your device?

**Comment by Zachzx0** [comment]
I just use the Demo Video

**Comment by Zachzx0** [comment]
> What do you mean you can't play the video the 'first time'?
> 
> Could you give us the specs of your video?
> 
> Does it play in the Demo_MediaPlayer scene on your device?

I just use the Demo Video

**Comment by Zachzx0** [comment]
> What do you mean you can't play the video the 'first time'?
> 
> Could you give us the specs of your video?
> 
> Does it play in the Demo_MediaPlayer scene on your device?

Maybe you can clone my demo ,and test it on Ios-device.

https://github.com/Zachzx0/AVProTest.git

the first time you click the right button . it just laod video but not palying .

**Comment by MorrisRH** [comment]
Looks like you're using the PlaylistMediaPlayer component. This had issues on iOS/macOS which have been fixed and will be available in the next release.

**Comment by AndrewRH** [comment]
AVPro Video 2.3.0 has been released and includes a fix for this issue.  Thanks,

**Comment by Zachzx0** [comment]
I just had upgraded to v.2.3.0.
but i found that the bug about https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1000 may be not fixed completed .

when i switch video quickly, it was crashed,both In IOS and Android now.
@AndrewRH

**Comment by Zachzx0** [comment]
And i found a strange Excepthon
![image](https://user-images.githubusercontent.com/41116914/148323951-ab4d62cd-ab3e-42fc-8a27-5664e0d2f972.png)
