### ISSUE TITLE
OES Rendering Path on Oculus Quest is rendering in a Sphere below the Camera instead of around the Camera

### ISSUE THREAD

**Issue by LB-Till** [RenderHeads/UnityPlugin-AVProVideo#1205]
**Issue description**
When trying to use OES Path with ApplyToMesh on Oculus Quest, the video is rendering on a small sphere below the camera instead of a sphere around the player. 

Also when choosing Multiview, the one eye gets an offset.

**My Setup**
 - Unity version: 2021.3.0f1 (LTS)
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  AVPro Video Android Core 2.5.2
 - Operating system version: Android - Oculus Quest (41.0.0.xxx)
 - Device model: Oculus Quest
 - Video specs (resolution, frame-rate, codec, file size):  Cones-360Mono-4K30-H264 from Demo Videos
 - URP 12.1.6
 - XR Plugin Management 4.2.1
 - Oculus XR Plugin 3.0.2

**To Reproduce**
1. Create an empty project, 
2. Import XR Plugin Management 4.2.1
3. Import Oculus XR Plugin 3.0.2
5. Import Universal Render Pipeline 12.1.6
6. Create and Add URP Pipeline Asset under Graphic Settings
7. import AVPro Video Core Android Edition 2.5.2
7. Set in Project Settings: 
  7a. Graphics API to "Open GLES3"
  7b. Color Space Linear
8. Create new Scene, add Tracked Pose Driver to Main Camera
9. Add AVPro Video - Media Player
9a. Add Video 
9b. In Platform Specific Settings - Android: Set Use OES Rendering to enabled
10. Copy "Sphere-ApplyToMesh" from Demo_360Stereo scene. (Should have 100,100,100 Scaling and Pos at 0,0,0)
10a. Fill in Media Player
10b. Swap Shader for the Demo-360 Material to InsideSphere Unlit - Android OES ONLY
11. Build Scene and Run.

**Logs**
-

**Screenshots**
Screenshots are ODH captures, so ignore the double eye effect.
![2022-06-14T16-02-47 933Z](https://user-images.githubusercontent.com/107492438/173623796-1876cc7b-5b08-4e1c-968a-8ae2f71094bb.png)
![2022-06-14T16-02-59 193Z](https://user-images.githubusercontent.com/107492438/173623801-3c23feb4-1c85-465b-87f0-7a2dcea332bc.png)

Screenshot with multiview 
![2022-06-14T16-07-34 165Z](https://user-images.githubusercontent.com/107492438/173624462-83bae1ae-ec7e-4c5b-bdfe-bc2403aefc93.png)

**Videos**
-

**Comment by Ste-RH** [comment]
When using MultiPass, do you have the UpdateMultiPassStereo.cs script on your main camera GameObject?

**Comment by Ste-RH** [comment]
I only have a Quest 2 to hand - which I wouldn't think should make a difference.

Following your steps exactly, I do not get what you are seeing.  I get a perfectly rendered sphere around the camera playing back the video as expected.

Can you email over the project you created so I can see what might be different?  If so, send it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com?subject=Issue#1205)

**Comment by LB-Till** [comment]
Ok, just confirmed that i do have the same issue on oculus quest 2. 

At this point, I assume i forgot a checkbox somewhere or used a weird setting. I've sent the project to you guys. 
Thanks in advance.

**Comment by Ste-RH** [comment]
Thanks for testing/confirming re Quest 2, and sending over a project.  Just downloading the Unity version to take a look and will respond shortly.

**Comment by Ste-RH** [comment]
The difference is quote simple.

You are not using the Mono sample video, you are using the Stereo sample video.  This is a top/bottom stereo packed.  If I change it to the Mono video, everything is rendered fine.  If I leave it as the stereo video and change the packing to top/bottom, everything is fine.

![image](https://user-images.githubusercontent.com/46531149/173828077-2c4478d1-1c87-437f-a13e-605e5855e5e5.png)

**Comment by LB-Till** [comment]
ok. I've just tested it. Set stereo packing to TopBottom, kept stereo video. Same Result. With double image when using multiview.
Also tried keeping stereo at none and taking the mono video. Same result.

**Comment by LB-Till** [comment]
Is there a shader to use the OES path on the skybox instead of the sphere? Might be an option if that is working.

**Comment by Ste-RH** [comment]
Multi Pass, Multiview, both OES and none-OES all behave exactly as they should do here.

The only other thing I did was zero the camera transform position...but that shouldn't do anything.

No, there is no skybox OES shader.  Only the special AVPro Video ones.

**Comment by Ste-RH** [comment]
Anything to report @LB-Till ?

**Comment by LB-Till** [comment]
Sorry for the late reply. We've had a bank holiday and a long weekend over here last thursday.

I've just created a new build. Reset camera and checked all the settings. Issue persists.

**Comment by LB-Till** [comment]
Ok, i think i found a quick fix. There seems to be an issue with the conversion of the model itself. I created a sphere in blender and it was tiny in the build. Once i increased the scale factor in the import settings, it has the increased size. 
So i assume, for some reason my import is not working correctly.

With the custom sphere i do have some clipping with the corners though, which is probably because my sphere isn't as smooth as yours?

**Comment by Chris-RH** [comment]
Yeah, in blender you need to make sure you've used the modifier "subdivision surface" and increase the levels. Also Object menu -> shade smooth.

Is it just your own sphere that is not rendering properly still or is it the default demoscene one?

**Comment by LB-Till** [comment]
Neither sphere is rendering correct in multiview (separate images for each eye). Multiview itself is working correctly though.
Default sphere is still rendering too small.
My own sphere is rendering fine, except for the smoothing issue (which can be probably solved easily, by increasing the polycount).

I tried all different combinations of shader and media player settings. And using both mono and stereo videos. To me it looks like an issue in the shader or shader execution, but i can't get my head around it. What or why its not working properly.


In the screenshots below you can see the difference between left and right eye. Both screenshots using the custom sphere. The cube is fine for both eyes, the video is separated. The yellow spot is a near plane clipping issue, that requires some finetuning. 

![2022-06-23T09-18-03 049Z](https://user-images.githubusercontent.com/107492438/175264937-91a49611-709e-4c65-b811-b969f09f5603.png)
![2022-06-23T09-18-14 719Z](https://user-images.githubusercontent.com/107492438/175264944-a8377cec-d428-45d6-a3b9-e93bee374f01.png)
![2022-06-23T09-20-34 866Z](https://user-images.githubusercontent.com/107492438/175264948-4b65082a-c7c2-4da5-80e6-05c8f1e74ceb.png)
![2022-06-23T09-20-57 356Z](https://user-images.githubusercontent.com/107492438/175264952-ce497ff7-7564-4adc-9cc6-3080735130cb.png)

**Comment by Ste-RH** [comment]
Can you [email](mailto:unitysupport@renderheads.com?subject=Issue#1205) over another project showing the above so we can take a look?

**Comment by LB-Till** [comment]
sure, but its still the same barebone project, just swapped out the video and the sphere.

**Comment by LB-Till** [comment]
sent it. Im really curious if you can reproduce it or not. Because if not, there must be something incredibly stupid im missing.

**Comment by Ste-RH** [comment]
Thanks for sending over the projhect.  I just want to make sure we are looking at the same baseline.

Building/running without any changes at all on a Quest 2...and grabbing a video via Android Studio, this is what I get:

https://user-images.githubusercontent.com/46531149/175299205-3bcb1309-e8c5-49c6-bb56-17116769d874.mp4

**Comment by LB-Till** [comment]
that looks pefectly fine to me. No shifted image. Just the near plane glitch, which we can ignore. 
what the hell is going on in my project

**Comment by Ste-RH** [comment]
> that looks perfectly fine to me. No shifted image.

That is what I thought

**Comment by LB-Till** [comment]
ok, i will do a completely new setup on a different computer. And see if i get the same issue there.

**Comment by LB-Till** [comment]
Tested on a different computer: 
Importing the project i sent you & building without changing anything: Exactly same issues as before
Setting up a clean & new project fixed the "tiny sphere" issue with the demo sphere. But im still having the shifted image issue. So at least now i can confirm, that the sphere scale and the multiview issue were separate issues.  
I also tested the apks on a different device (quest 2) to rule out its a device issue.

I will continue to investigate the issue, but im absolutely confused whats happening here.

**Comment by LB-Till** [comment]
My findings so far: Using the URP Pipeline Asset in Graphic Settings leads to the "tiny sphere". Removing it, displays the sphere in the regular (working) size.

**Comment by LB-Till** [comment]
thanks, i'll give it another try.

**Comment by LB-Till** [comment]
unfortunately its still the same. Im pretty sure the URP Global Settings gets generated automatically when assigning the URP Asset to Graphics though.

Could there be an issue during the build process maybe? Are you using the Android SDK shipped with Unity?
Or could it be some sort of issue with a unity package that may gets autoloaded for my projects? 
This all makes absolutely no sense 😕 


Also what i've noted, that after building unity has done some changes with the x86 .so files in the android folder eventhough ARM64 is selected as target architecture. I have no idea if that is normal, i just found it odd.

![image](https://user-images.githubusercontent.com/107492438/176677580-def59d41-977a-49e0-860b-e5be1e358192.png)
![image](https://user-images.githubusercontent.com/107492438/176677556-2386f17a-7e76-492e-8ee2-257f4c7dd2f1.png)

**Comment by Ste-RH** [comment]
> Are you using the Android SDK shipped with Unity?

I used a complete stock fresh install of the Unity version you said you were using.

The x86 is metafile differences.  Interesting as I would actually expect to see no changes, or more than just x86.  That is something I will look into...but it will be nothing to do with the odd things you are seeing.  You could delete the x86 and x86_64 folders and it will (should!) have no impact/difference.

**Comment by Ste-RH** [comment]
Your architecture screen grab is interesting.  Are you building with IL2CPP?  By default Unity sets the Mono scripting backend.  Only by changing it to IL2CPP can I then set ARM64.  As you never stated a scripting backend change I have always left it on Mono.  Will try IL2CPP now...

**Comment by Ste-RH** [comment]
Again, exactly as it should be.

**Comment by Chris-RH** [comment]
Are you still having issues with this @LB-Till ?

**Comment by LB-Till** [comment]
hey, 
we were not able to resolve the problem.
For now we are just not using the OES render path.

**Comment by Ste-RH** [comment]
@LB-Till We are pretty sure the issue you were seeing is the same as #1342 and should be addressed in the next release.

**Comment by LB-Till** [comment]
Great to hear! Thanks for the heads up!

**Comment by JuanObiJuan** [comment]
This is still present in current version.

My setup is basically (for Oculus Quest 2) the scene included in the demo_360 replacing the camera for the Oculus Quest Camera Rig prefab included in the oculus integration package:

Stereo Rendering Mode: Multipass settings on Android

Media player with OES activated

Material in the sphere: Demo-360 with the shader "AVPro/VR/InsideSphere Unlit Transparent (stereo+color+alpha) - Android OES ONLY"

AVPro Video: v2.6.7 (plugin v2.6.7f1-ultra)

Target Platform: Android

Unity: v2020.3.43f1

Oculus Camera Rig with Update Multipass Stereo script attached to the center eye Anchor (Camera)

Render URP

Playing video "Cones-360Stereo-2K30-H264.mp4"

I tried just before installing the URP packages and the video looks all right.

The same scene, but installing URP package (and setting URP assets, quality, etc on the project), the final reuslt change to the camera on the top of the sphere like in the pictures attached. Doesnt matter how big you make the sphere there is no change.

The same scene but returning to multiview, disabling Android OES and using shader "AVProVideo-VR-InsideSphere-Transparent" everything comes back to how it should and working as expected.

**Comment by Ste-RH** [comment]
I wonder if it is linked to #1416.  Can you grab the early-test-fix I just posted into that issue and give it a test @JuanObiJuan ?

**Comment by JuanObiJuan** [comment]
Hi @Ste-RH. Same settings with the updated shaders and script from https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1416#issuecomment-1372546804 and the result is the same.

Camera is still on the top of the sphere.

**Comment by Ste-RH** [comment]
Can you send over a project that reproduces this? As usual, to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Ste-RH** [comment]
I _think_ this is the same issue as seen in #1613 .  There is a fix posed in there that might be worth trying @LB-Till @JuanObiJuan

**Comment by Chris-RH** [comment]
Have you had any luck with that @JuanObiJuan ?

**Comment by Ste-RH** [comment]
Closed due to lack of response.
