### ISSUE TITLE
HLS with H.265 codec file does not show the image in media player on iOS

### ISSUE THREAD

**Issue by Kibisi** [RenderHeads/UnityPlugin-AVProVideo#1544]
**Describe the issue**
I stored HLS file with H.265 codec file in the cloud server.
When I play it in media player on iOS, the image is black (audio and time frame is coming). iPad 
On Androide wiht Exo player, it can play wihtout any problem
**Your Setup (please complete the following information):**
 - Unity version: 2022.2.12
 - AVPro Video version:  2.7.3  ultra
 - Operating system version: iOS 16.3
 - Device model: iPhone 12 Pro, iPad 9th generation
 - Video specs (resolution, frame-rate, codec, file size):  resolution: any, frame-rate: any, codec: H.265 (iPhone or iPad camera caputure default setting), file size: any

**To Reproduce**
1. Capture the video in iPhone
2. Covert the video to HLS with ffmpeg
3. Upload the HLS file, and get URL of it.
4. Play the HLS file via media player on iOS app by calling  the below method.
 mediaPlayer.OpenMedia(new MediaPath(HLSurl, MediaPathType.AbsolutePathOrURL), autoPlay: true);

**Comment by Chris-RH** [comment]
have you got any test stream URLs?
Does the video play if it is played from the device itself? ie not streamed.
What are the video specs?
Have you followed Apple's HLS authoring guidelines? https://developer.apple.com/documentation/http_live_streaming/http_live_streaming_hls_authoring_specification_for_apple_devices

**Comment by MorrisRH** [comment]
It's an issue with 10bit output and has now been fixed.

**Comment by Kibisi** [comment]
Dear all, thank you for your message. 
- have you got any test stream URLs?: No due to I do not have any for it.
- Does the video play if it is played from the device itself? ie not streamed. : Streamed.
- What are the video specs? : 1: m4s x HRD, 2: m4s x SD, 3: TS x HRD, 4: TS x SD
- Have you followed Apple's HLS authoring guidelines? : I tryed to apply to create m4s type HLS.

If this proble is came from your product, I am looking forward to fix it. (For now, when I use H.265 data for HLS, I will convert H.264 before converting HLS with ffmpeg).

**Comment by Chris-RH** [comment]
This should now be fixed in 2.8.0

**Comment by Kibisi** [comment]
Thnak you for your updating. I tryed to test by using 2.7.3 to 2.8.4, but the problem was not solved ( Still same sutiaion was happened). Could you provied any solution? There is any specific setting?
