### ISSUE TITLE
Crash using short videos in Playlist Demo Scene

### ISSUE THREAD

**Issue by Helath2605** [RenderHeads/UnityPlugin-AVProVideo#1977]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Replacing the videos in the demo scene with short looping videos causes unity to crash after a while. The demo videos seem to work fine, and only happens when using either short videos, or maybe something with how we are exporting them.

**Your Setup (please complete the following information):**
 - Unity version: v2022.3.7f1 WindowsEditor
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v3.0.8 (plugin v3.0.8f1-core)
 - Operating system version: Windows 10 19044.4780
 - Video specs (resolution, frame-rate, codec, file size): 
     -6 videos across two displays. 
     -All at 1920x2160 and around 30fps frame rates.
     -.mp4 extensions
     - all videos less than 6MB

**To Reproduce**
1. Open Demo Scene
2. Set Windows platform Settings to the following
 -WinRT API
 -Hardware Decoding enabled
 -Use Render Sync off
3. Set to play short videos (1-2 seconds)
4. Will crash within 12 hours

**Logs**
[Crash.txt](https://github.com/user-attachments/files/16768428/Crash.txt)
I can post the full log and dump if needed.

**Comment by Chris-RH** [comment]
Does the issue occur using MediaFoundation and DirectShow API?
Are you able to provide the video(s) you are using for testing please? either here or to unitysupport@renderheads.com

**Comment by RichRH** [comment]
Just a slight side note here that 'Hardware Decoding' and 'Render Sync' _only_ affect Media Foundation playback, not WinRT (which has relatively few options)

**Comment by Helath2605** [comment]
Email sent, relevant info in the copy:
In the Demo scenes folder I duplicated and modified the playlist scene to allow 2 monitors and multiple videos. The scene is called Demo_Playlist_Modded and it is the one that is crashing.
Is also has a button to swap scenes since we noticed that for Media Foundation the graphics driver would crash at some point, but unity would still work until you tried to change scenes and it would crash. No useful information from the unity logs except for reports of dx11 unable to create textures and just an 887A0006 error from windows event logs.

**Comment by RichRH** [comment]
Thanks for the confirmation @Helath2605 - I actually found both editor and build wouldn't advance past the first video for me if using WinRT, but I've found a possible cause and added a fix that should make it into the next release.

Will leave the build running overnight with a debug version of AVPro to see if I can catch any crashes..

**Comment by RichRH** [comment]
Hi @Helath2605,

FYI.. we're _hoping_ to release a build today that should fix the WinRT first-time looping issue.

I ran your WinRT build overnight though the debugger and did encounter a crash - it seemed to fail within the allocation of WinRT's internal video player with an out of memory exception, but the process itself was only using about 160Mb so there's the possibility it's something more at system level.

I'll keep investigating but this might take some time - you might want to keep an eye on https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1692, especially the last few posts, as yours seems to be a similar issue to TatsuyaPan (I may merge the two issues). Note they've had similar issues with the Unity video player itself which may also suggest more system-level problems, and it seems the most stablity for small/looping videos currently comes from Media Foundation _without_ 'Hardware Acceleration' enabled.

Cheers,

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.10 has been released.  Please update and retest to see if there is any improvement.

**Comment by Helath2605** [comment]
Still crashing, but this time it's actually reporting the memory leak to task manager.
In the demo project I sent you I updated to 3.0.10 and made it run the Demo_Playlist_Modded scene. Changed the active players to Media Foundation and turned Hardware Acceleration and RenderSync **off**. In about an hour the Project crash and was using 10GB of RAM.

**Comment by RichRH** [comment]
Hi @Helath2605,

Thanks for the update - just to confirm, the only fix in version 3.0.10 related to this issue is for WinRT failing to loop. I'm still looking into the crash side of things.

Cheers,

**Comment by Helath2605** [comment]
Not sure if this helps, but it seems as though just repeatedly opening and closing videos will cause a leak as well. And it that is the case it would make sense why we might be seeing it with shorter videos that rapidly open and close.

This is the script I used

```
using RenderHeads.Media.AVProVideo;
using System.Collections;
using UnityEngine;

public class QuickLoadAndUnload : MonoBehaviour
{
    [SerializeField] MediaPlayer Player;

    void Start()
    {
        StartCoroutine(Run());
    }

    IEnumerator Run()
    {
        while (true)
        {
            Player.OpenMedia(new MediaPath("AVProVideoSamples/RenderHeads-1080p30-H264.mp4", MediaPathType.RelativeToStreamingAssetsFolder), false);
            yield return new WaitForSeconds(1);
            Player.CloseMedia();
            yield return new WaitForSeconds(1);
        }
    }
}
```

Settings:
![image](https://github.com/user-attachments/assets/92b83f69-c512-4bfd-9329-3dd42c396bd7)


And in about 30 mins we were already using over 2GB on the target machine. Can also see a leak in the editor.

**Comment by Helath2605** [comment]
Hey, has there been any updates for this issue?

**Comment by Chris-RH** [comment]
We'll update this thread when we have any news :)

**Comment by RichRH** [comment]
Hi @Helath2605,

Quick update - I believe I've located a fairly major leak in Unity (and the way it wraps native textures) linked to the above, at least with rapid loading of videos under MF (not sure it'll impact WinRT). I'm looking into fixing/compensating for it at native level and will update this ticket when I have more information.

Cheers,

**Comment by RichRH** [comment]
Hi @Helath2605,

Another update - I've tracked down a leak in WinRT/Windows which was causing the above crash and have added a workaround which will be in the next release (hopefully within the next week).

Cheers,

**Comment by wybo** [comment]
Looking forward to the MF leak fix! Here from #1936

**Comment by wybo** [comment]
Any chance the 3.0.12 update can be done soon, as it would be great to finally be rid of the memory leak!

**Comment by Helath2605** [comment]
I would also love an update if there is one :)

**Comment by Ste-RH** [comment]
@wybo @Helath2605 We are aiming to release the next update this coming Friday.  Currently this will be 3.1.0.  We will message this thread when we get the release out.  Sorry for the delay.

**Comment by wybo** [comment]
Great to hear!

Especially hope the Media Foundation fix will work with hardware decoding! As some of my users are from Latin America & other areas where they might not have the newest / fastest hardware.

**Comment by Helath2605** [comment]
Are we still looking for a release soon or is it going to be a while?

**Comment by Chris-RH** [comment]
Its looking like mid-end of this week if everything goes well :D

**Comment by Ste-RH** [comment]
Apologies it has not been released yet.  We have hit a number of unforeseen issues as we have approached release.  These have all taken longer to address than we had hoped.  As Chris says...hopefully this week.

**Comment by Ste-RH** [comment]
AVPro Video v3.1.0 has just been released. Please do report back if the fixes in the version address the issue.

**Comment by wybo** [comment]
I've updated to v3.1.0 and ran my app for 3 long sessions. Two of 4 hours, and one of six, and while there's still a small increase of max 300 mb in that timespan (which could be anything else), the main issue of ballooning memory usage by GBs followed by crashes is gone!

Thanks a lot for fixing this!

**Comment by wybo** [comment]
Done!
https://assetstore.unity.com/packages/tools/video/avpro-video-v3-core-edition-278893#reviews

Am still curious how it was fixed, and especially whether the workaround / fix affects support for hardware decoding or not in Media Foundation

**Comment by Helath2605** [comment]
Everything I looking good on our end so far as well. Sorry for the late response, we were having weird texture reference issues and I wanted to make sure it wasn't related to the plugin. However it seems to be just a driver issue, so I think we are good!

**Comment by Ste-RH** [comment]
@wybo Many thanks for your review.  We have left a reply to it with some more information on the fix we had to put in place.  Here is the main of that for anyone else interested:

> The root cause of the main leak is actually a change Unity themselves made, not something that existed in AVPro Video (historically per se).  The change Unity made was regarding how they reference count native (external) textures.  We were unaware of the change they made, certainly we could not find any public facing declaration of the change and it may even be a bug in Unity!  The change we made at AVPro Video plugin level was to add special case code to handle this change/bug in reference counting.  The whole process of getting to a reliable fix was elongated due to this issue only happening in some versions of Unity.
