### ISSUE TITLE
[macOS] Top-bottom alpha packed videos render incorrectly

### ISSUE THREAD

**Issue by rhduwe** [RenderHeads/UnityPlugin-AVProVideo#2062]
### Unity version

6000.0.23f1

### Unity editor platform

macOS

### AVPro Video edition

Ultra

### AVPro Video version

3.1.2

### Device hardware

Mac mini M2 Pro 16GB

### Which macOS version are you using?

15.0.1

### Texture format

BGRA

### Audio output

System Direct

### Which output component(s) are you using?

All output components seem to share this behaviour

### The issue

The top-bottom Alpha-packed videos are displayed incorrectly. I think AVPro uses the top half of the video as the mask and the bottom half as the content. 

Steps to reproduce: 
1. Create a new project from the template Universal 3D
2. Import AVPro 3.1.2
3. Open the demo scene "Demo_MediaPlayer"
4. Replace the video reference in MediaPlayer with "Sample-Local-MP4-Cones-Transparent"
5. Press play

![Screenshot](https://github.com/user-attachments/assets/082e4ce0-d19f-4a2a-925a-ded9159822d5)

Notes: 
- Videos with left-right packing work fine.
- I'm seeing the same problem on Vision Pro 
- Windows/Android are unaffected

**Comment by MorrisRH** [comment]
Thanks for finding this, unintended consequence of fixing another issue. This has been fixed and will make it into the next release (version 3.1.3).

**Comment by rhduwe** [comment]
Yep, that fixes it, at least for macOS and visionOS

**Comment by DarkMatterZA** [comment]
hi this issue is not resolved for android, specifically the meta quest 3. the exact same happens on the quest.

**Comment by DarkMatterZA** [comment]
@Chris-RH will you please reopen

**Comment by Chris-RH** [comment]
There is a fix for this in our next release, which should be out any day now.
