### ISSUE TITLE
[iOS] Video with rotation metadata playing with wrong rotation

### ISSUE THREAD

**Issue by CyberChroma** [RenderHeads/UnityPlugin-AVProVideo#2092]
### Unity version

v2022.3.53f1

### Unity editor platform

Windows

### AVPro Video edition

Ultra

### AVPro Video version

2.9.3

### Device hardware

iPad Pro

### Which iOS version are you using?

18.1.1

### Texture format

BGRA

### Audio output

System Direct

### Which output component(s) are you using?

Playlist MediaPlayer

### The issue

Problem description:

Certain videos with rotation metadata do not display with the correct orientation in the media player. For example, videos recorded using an iPad's native recorder experience this issue. When these videos are imported and processed using FFmpeg, they are converted to the correct orientation. However, when playing the raw, unprocessed videos, the orientation remains incorrect. Our application runs on both Windows and iOS platforms. On Windows, setting the VideoApi to MediaFoundation in the media player resolves the rotation issue, displaying videos correctly. However, using DirectShow results in incorrect orientation. Similarly, the videos display with incorrect rotation when played on a MacBook in the Unity Editor or on iOS devices. We can work around this issue on Windows, but we are mostly trying to get this working on iOS.

Device (which devices are you having the issue with - model, OS version number):

Windows, MacOS, iOS

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

The videos in question are just screen recordings on an iPad. The important part is that the metadata has a rotation, in this case 180.

System Information:

AVPro Video: v2.9.3 (plugin v2.8.5f1-ultra)
Target Platform: iPhone
Unity: v2022.3.53f1 WindowsEditor
OS: Desktop - MS-7D91 (Micro-Star International Co., Ltd.) - Windows 10  (10.0.19045) 64bit - English
CPU: 13th Gen Intel(R) Core(TM) i9-13900 - 32 threads - 65312KB
GPU: NVIDIA GeForce RTX 3090 - NVIDIA - Direct3D 11.0 [level 11.1] - 24326KB - 16384

### Media information

https://github.com/user-attachments/assets/d4517775-2e9a-4a65-a4dc-d099693c1111

**Comment by Ste-RH** [comment]
AVPro Video v2.9.3 was deprecated in Q1 of this year and subsequently will no longer receive updates.

We advise you test your use-case/assets in the latest v3.x trial version to see if the issue still persists for you (we will, naturally, schedule some testing time for this as well with the asset you provided).  If it does, we can look to address the issue in the v3.x codebase.

**Comment by Ste-RH** [comment]
Confirmed this happens in v3.x in Windows using the DirectShow API.

**Comment by Ste-RH** [comment]
Confirmed this happens in v3.x on Android when using the MediaPlayer API (both BGRA and OES).

**Comment by Ste-RH** [comment]
> We've made the upgrade to 3.1.3 (Using the new asset, AVPro Video v3 - Ultra Edition), so we no longer need support for the 2.x version, but this issue seems to be still happening in the latest version.

Thanks for the update.  We will look into this asap on Apple platforms.

**Comment by MorrisRH** [comment]
Fixed for macOS and iOS. Issue with the DisplayIMGUI component not applying the texture transform.

**Comment by CyberChroma** [comment]
I tried the latest version, made sure to do a fresh install, but I'm still seeing this particular video file being upside down. I've tried on Windows and iOS. On Windows, it seems DirectShow is playing it upside down, but MediaFoundation is playing it properly.

**Comment by Chris-RH** [comment]
Are you able to send us a copy of the particular video that is having issues please? unitysupport@renderheads.com

**Comment by CyberChroma** [comment]
I included the video in my initial post, but I'll post it again here. It seems to be basically any recording on a mobile device where it takes the rotation of the device into account. Looking at the metadata of this video, it has stored a rotation of -180 degrees. This particular video I also cropped to 16:9:
https://github.com/user-attachments/assets/b849467c-09e3-4b70-873a-3ee6b64827b7

And here's a screenshot in our program in-editor showing that the video is upside down:
![image](https://github.com/user-attachments/assets/af754a8f-8811-485e-8504-5fcf127dffe9)

And proof that we are using AVPro Video 3.2.0:
![image](https://github.com/user-attachments/assets/36fff98c-9e31-4e82-9206-7e42f6abeddf)

And looking at the metadata of the video, it has stored a rotation of -180 degrees

**Comment by Ste-RH** [comment]
> I tried the latest version, made sure to do a fresh install, but I'm still seeing this particular video file being upside down. I've tried on Windows and iOS. On Windows, it seems DirectShow is playing it upside down, but MediaFoundation is playing it properly.

@CyberChroma  So this issue is fixed on iOS with the fixes made in v3.2.0?  But still remains an issue in Windows using DirectShow only?

**Comment by CyberChroma** [comment]
It's still broken on iOS, Windows was just easier to screenshot as an example. What I said is still true, DirectShow has it upside down, MediaFoundation flips it properly. But on iOS, it's broken and upside-down no matter what

**Comment by Ste-RH** [comment]
Are you using a custom shader?

**Comment by CyberChroma** [comment]
We do have a custom script that Blits the AVPro feed to a rendertexture, but it uses one of the AVPro shaders, AVProVideo/Unlit/Opaque (texture+color+fog+stereo support)

**Comment by Ste-RH** [comment]
Are you setting the texture matrix correctly @CyberChroma ?

![image](https://github.com/user-attachments/assets/e351e1b1-44e2-4570-98a7-b1de3650b7f3)

![image](https://github.com/user-attachments/assets/0c2e50dc-9f17-4fae-9031-d35fb6b170cd)

**Comment by CyberChroma** [comment]
Sorry for the late reply, I've been going through old code I didn't write to figure out how we interface with AVPro and at what point things seem to be breaking. To give more context on how we are extracting the textures, we grab the current texture of the video with MediaPlayer.TextureProducer.GetTexture(), and MediaPlayer.TextureProducer.RequiresVerticalFlip() to know to flip it for the coordinate system. We then blit the texture with a function that looks like this:

            ToolUtils.CustomBlitTexture(texture, FingerWorks.Backgrounds.backgroundRenderTexture, _mediaPlayer.TextureProducer.RequiresVerticalFlip(), _deinterlaceMaterial);


    public static void CustomBlitTexture(Texture source, RenderTexture destination, bool flip = false, Material mat = null, int renderPass = -1)
    {
        if (!mat && !flip && CanFastCopy(source, destination))
        {
            Graphics.CopyTexture(source, destination);
            return;
        }

        GL.PushMatrix();
        GL.LoadPixelMatrix(0, source.width, source.height, 0);

        Rect texRect = flip ? new Rect(0.0f, source.height, source.width, -source.height) : new Rect(0.0f, 0.0f, source.width, source.height);
        Graphics.SetRenderTarget(destination);

        if (mat)
            Graphics.DrawTexture(texRect, source, mat, renderPass);
        else
            Graphics.DrawTexture(texRect, source);

        GL.PopMatrix();
        GL.InvalidateState();
    }


Based on your suggestions I've tried setting up VideoRender.SetupMaterialForMedia, and VideoRender.SetupTextureMatrix before blitting, both of which seem to have no effect on the orientation of the video.

To debug this further, I tried just setting the texture as a simple raw image on a canvas. The texture I get from this is different depending on if I'm using MediaFoundation or DirectShow. I've written below what transformation this texture would need to be upright:

MediaFoundation:
Regular video -> Flipped vertically
iPad recorded video -> Flipped vertically

DirectShow (or iOS):
Regular video -> Flipped vertically
iPad recorded video -> Flipped horizontally

So even this raw texture behaves differently depending on the video API. I know the texture at this stage is flipped vertically even on normal videos because as part of the blip a vertical flip is applied to account for Unity's coordinate system being different. Anyway, if the video needs to extract the rotation metadata to apply it to the texture, I'm not sure at what stage in the process that's supposed to happen and where I should be looking, but it looks like when the texture is first extracted the 2 video APIs are already rotating the texture differently, so on one it already has the wrong rotation unless I'm misunderstanding. Sorry for the long reply, I'm sure not all of this is relevant, just trying to narrow down where this issue is coming from, and whether the issue is just from our own code.

Thanks again for the help!

**Comment by MorrisRH** [comment]
On Apple platforms we now handle the orientation correction internally when using the BGRA texture format so you shouldn't need to apply the texture transform. This will be available from the next release 3.2.1.

**Comment by Ste-RH** [comment]
We cannot offer a fix for this for DirectShow on Windows at this time.  We would always recommend that, unless you have a very specific/valid reason to use DirectShow, developers use wither MediaFoundation or WinRT on Windows.

**Comment by Chris-RH** [comment]
AVPro Video version 3.2.1 has been released.  Please let us know if this has not resolved your issue.

**Comment by CyberChroma** [comment]
Sorry had a busy week, it looks like it's finally working on iOS! Thank you!

**Comment by Chris-RH** [comment]
Not a problem.  Have a great weekend :)
