### ISSUE TITLE
Failed to create player

### ISSUE THREAD

**Issue by crazylulu9999** [RenderHeads/UnityPlugin-AVProVideo#37]
**Describe the bug**
Using AVPro Video for splash scene.
Quit app and restart app quickly then "Failed to create player".

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.11f1
 - AVPro Video version: 1.9.12
 - Operating system version: Android 8.1.0
 - Device model: Redmi Note 5
 - Video specs (resolution, frame-rate, codec, file size): Any

**To Reproduce**
1. Quit app using Application.Quit()
2. Re-start app quickly

**Logs**
```csharp
[AVProVideo] Failed to create player instance 
UnityEngine.Logger:Log(LogType, Object)
RenderHeads.Media.AVProVideo.AndroidMediaPlayer:.ctor(Boolean, Boolean, VideoApi, Boolean, Audio360ChannelMode, Boolean)
RenderHeads.Media.AVProVideo.MediaPlayer:CreatePlatformMediaPlayer()
RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
RenderHeads.Media.AVProVideo.MediaPlayer:Start()

[AVProVideo] Initialising AVPro Video (script v1.9.12 plugin v1.9.10) on Adreno (TM) 509/OpenGL ES 3.2 V@269.0 (GIT@a1355e2, I141a912644) (Date:04/18/18) (MT True) on Android 
UnityEngine.Logger:Log(LogType, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
RenderHeads.Media.AVProVideo.MediaPlayer:Start()

[AVProVideo] Opening jar:file:///data/app/com.test.app-jOTKGt8J8Fpxlbv1qx4j1Q==/base.apk!/assets/video/downloaded_from_google_play.mp4 (offset 0) 
UnityEngine.Debug:Log(Object, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile()
<PlayCoroutine>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[AVProVideo] m_Video is null! 
UnityEngine.Logger:Log(LogType, Object)
RenderHeads.Media.AVProVideo.AndroidMediaPlayer:OpenVideoFromFile(String, Int64, String, UInt32, UInt32, Int32)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile()
<PlayCoroutine>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[AVProVideo] Failed to open jar:file:///data/app/com.test.app-jOTKGt8J8Fpxlbv1qx4j1Q==/base.apk!/assets/video/downloaded_from_google_play.mp4 
UnityEngine.Debug:LogError(Object, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile()
<PlayCoroutine>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by parmaia** [comment]
Hello!

I'm facing the exact same issue. If I close the app with Application.Quit(); during the video play, then I can re open it with no problem. If I close the app after the video finishes playing, then I got the message: "[AVProVideo] Failed to create player instance".

**Comment by AndrewRH** [comment]
We've just released a new version of AVPro Video (v.1.9.17) which should fix this issue. Please do test it and let us know if if this resolves it for you.

Thanks,

**Comment by AndrewRH** [comment]
We'll close this issue in a couple of days, as we've proposed a solution (new plugin version) but haven't heard anything back.  If you're still having this issue with the new version please do let us know.

Thanks,

**Comment by joker-gizmo** [comment]
The issue still persist after update.

My setup:

Unity version: 2018.4.2f1
AVPro Video version: 1.9.17
Operating system version: Android 8.0.0
Device model: Samsung S8

[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/3311287/log.txt)

**Comment by AndrewRH** [comment]
@joker-gizmo 
Thanks for reporting this - could you provide more details on how to replicate this issue?

**Comment by joker-gizmo** [comment]
The problem was with another native plugin which is not terminate their thread correctly on quit. There was a bunch of errors on quit and after restart no one plugin was able to init. Sorry, for misleading you

**Comment by AndrewRH** [comment]
Great to hear you found the issue, i'll close this ticket now

**Comment by parmaia** [comment]
Hi!

Sorry for the delayed response.

I tested the new version (1.9.17) and have to say that the problem is still present. I made a small test project to show the issue, and realized that I'm when the video ends I disable the GameObject with the MediaPlayer attached and that is causing the problem. If I don't disable the GameObject or quit the app before the video ends, all goes fine.

To reproduce:

1. Create a new project and import AvPro 1.9.17.
2. Add a MediaPlayer, a Display UGui and link them so a video can be viewed. For simplicity let AutoOpen and AutoPlay to true. Add a video (any from StreamingAssets will work).
3. Create a GameObject and attach this script:
```csharp
using RenderHeads.Media.AVProVideo;
using UnityEngine;
    
public class Manager : MonoBehaviour{
    public MediaPlayer player;

    void Start() {
        player.Events.AddListener(PlayerEvent);
    }

    void Update() {
        if(Input.GetKeyDown(KeyCode.Escape)){
            Application.Quit();
        }
    }

    public void PlayerEvent(MediaPlayer player, MediaPlayerEvent.EventType eventType, ErrorCode error){
        switch(eventType){
            case MediaPlayerEvent.EventType.FinishedPlaying:
                player.CloseVideo(); // The problem occurs regardless of this line
                player.gameObject.SetActive(false); // <-- If you remove this line, the problem dissapears.
            break;
        }
    }    
}
```
4. Attach the script to the new GameObject.
5. Attach the MediaPlayer to the Manager script.
6. Compile and run the app on Android.
7. When the app start, let the video play to the end and press back button to quit the app.
8. Launch the app again, the app will freeze and the logcat shows:
`[AVProVideo] Failed to create player instance`

If you want I can send you the project I made to test it.

Thanks!

**Comment by ColorTwist** [comment]
Also receiving this issue on Android 9 with unity 2019.1.11f, happens usually after  `Application.Quit(); `and returning and running the game again. very annoying to players.
using the latest version 1.10.0

Any fix for this or maybe should i use something to dipose AVPRO on Application.quit?
> 
> 09-30 21:08:56.848: E/Unity(5478): Unable to find libc
> 09-30 21:08:56.882: E/Unity(5478): [AVProVideo] Failed to create player instance
> 09-30 21:08:56.882: E/Unity(5478): RenderHeads.Media.AVProVideo.AndroidMediaPlayer:.ctor(Boolean, Boolean, VideoApi, Boolean, Audio360ChannelMode, Boolean)
> 09-30 21:08:56.882: E/Unity(5478): RenderHeads.Media.AVProVideo.MediaPlayer:CreatePlatformMediaPlayer()
> 09-30 21:08:56.882: E/Unity(5478): RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
> 09-30 21:08:56.882: E/Unity(5478): RenderHeads.Media.AVProVideo.MediaPlayer:Start()
> 09-30 21:08:56.882: E/Unity(5478):  
> 09-30 21:08:56.882: E/Unity(5478): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

**Comment by AndrewRH** [comment]
Hmm...seems that this issue is still happening (sorry we only noticed now as we don't get notifications on Closed issues)

**Comment by ColorTwist** [comment]
Yes, it does :\ Whatever I tried to clean AVProVideo before quit game did not work.

**Comment by ColorTwist** [comment]
Any update on this?
I'll do note that I do open a few instances of AVProVideo in order to pre-prepare a video in a sequence.
If I ` Application.Quit()` without init any video the problem does not occur.

**Comment by parmaia** [comment]
Hi, 

I can confirm that this is still happening.

My workarround was to quit the app using Android native code:

 ```csharp
	public static void QuitApp(){
	#if UNITY_ANDROID
		AndroidJavaClass player = new AndroidJavaClass("com.unity3d.player.UnityPlayer"));
		androidActivity = player.GetStatic<AndroidJavaObject>("currentActivity");
		if(androidActivity!=null){
			androidActivity.Call("finishAffinity");
			AndroidJavaClass System = AndroidNativeInterface.GetClass("java.lang.System");
			System.CallStatic("exit", new object[]{0});
		}
	#else
		Application.Quit();
	#endif
	}
```

This is working on Unity 2019.1.14f1

**Comment by ColorTwist** [comment]
@parmaia  thanks for the update.

**Comment by ColorTwist** [comment]
@parmaia For some reason, i get an error on:
`AndroidJavaClass System = AndroidNativeInterface.GetClass("java.lang.System");`
'AndroidNativeInterface' does not exist in the current context

**Comment by parmaia** [comment]
@ColorTwist sorry, I kind of messed up with my sample code. I have a class for native calls and one line went into my sample code.

This code is tested and fully functional in Unity 2019.1.14f1.

``` csharp
    public static void QuitApp(){
    #if UNITY_ANDROID
        AndroidJavaClass player = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
        AndroidJavaObject androidActivity = player.GetStatic<AndroidJavaObject>("currentActivity");
        if(androidActivity!=null){
           androidActivity.Call("finishAffinity");
           AndroidJavaClass system = new AndroidJavaClass("java.lang.System");
           system.CallStatic("exit", new object[]{0});
        }
    #else
        Application.Quit();
    #endif
    }
```

I tested this on Unity 2018.4.2f1 and Untiy 2019.1.14f1 and on Android 8 and Android 9.

Again, sorry for the mistake.

**Comment by nsmith1024** [comment]
Shoiuld I replace "com.unity3d.player.UnityPlayer" with my package name to make it work for me?

**Comment by nsmith1024** [comment]
I have this problem too, but I dont have any native code, is there way to do it from C# in unity?

**Comment by parmaia** [comment]
@nsmith1024 You can use the QuitApp() method in my previous comment. It is C#.

**Comment by nsmith1024** [comment]
OK, thanks i w ill try it, i was wondering should I replace "com.unity3d.player.UnityPlayer" with my app package name? what about "currentActivity" do i have to change that?

**Comment by RenderHeadsSte** [comment]
Closing due to inactivity
