### ISSUE TITLE
2.1.6 PlaylistMediaPlayer not playing media via scripted correctly

### ISSUE THREAD

**Issue by z79422957** [RenderHeads/UnityPlugin-AVProVideo#867]
issue from: forum.unity.com
unity version 2019.4.17f1c1
Windows10-64
AVPro Video2.1.6

**2021/7/13**
https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-93#post-7322635
I used the playlistMediaPlayer script of AVPro Video2.1.6,then I created item of playlist items in c# code.Item is correct,but MediaPlayerA and MediaPlayerB warns no media specified at runtime.What can I do?Is it a question of the order of execution?Thank you.

AVPro Video2.1.3 doesn't seem to have such a problem.
If I enable auto open of MediaPlayerA and MediaPlayerB,it will report an error:
[AVProVideo] No file path specified
UnityEngine.Debug:LogError(Object, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:481)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(MediaPathType, String, Boolean) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:347)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI_Source() (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor_Source.cs:63)
RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection:Invoke() (at Assets/AVProVideo/Editor/Scripts/AnimCollapseSection.cs:51)
RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection:Show(AnimCollapseSection, Int32) (at Assets/AVProVideo/Editor/Scripts/AnimCollapseSection.cs:146)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI_Settings() (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:409)
RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection:Invoke() (at Assets/AVProVideo/Editor/Scripts/AnimCollapseSection.cs:51)
RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection:Show(AnimCollapseSection, Int32) (at Assets/AVProVideo/Editor/Scripts/AnimCollapseSection.cs:146)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI() (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:377)
UnityEngine.GUIUtility:processEvent(Int32, IntPtr)
![image](https://user-images.githubusercontent.com/16982190/126059801-a897cc88-82cc-48a4-b3cc-1deea28b2349.png)
![image](https://user-images.githubusercontent.com/16982190/126059807-af0027e1-67b5-4e26-abc6-b8deca924c58.png)
![image](https://user-images.githubusercontent.com/16982190/126059811-ec9549ba-d370-4fc0-99c4-64ae86922b7c.png)
![image](https://user-images.githubusercontent.com/16982190/126059818-66de418e-736d-4041-8a9f-600dbd469251.png)

**2021/7/14**
https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-94#post-7323070
Auto open is disabled, but the path still cannot be obtained. If I manually add an item of playlistmediaplayer in the inspector panel, mediaplayerA and mediaplayerB can get the path correctly.

![image](https://user-images.githubusercontent.com/16982190/126059865-28e15b63-b99a-4c4f-aaed-e6e3870aea57.png)

**2021/7/14**
https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-94#post-7326235
After manually creating items by C #, which method should I call manually? Or what?
![image](https://user-images.githubusercontent.com/16982190/126060059-4a2355c9-8040-4498-8423-0e227a6aa4d3.png)

**2021/7/15**
https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-94#post-7328869
at run time,I instantiate the prefab of playlistmediaplayer, mediaplayerA, mediaplayer B and displayugui first, and then add the playlist items of playlistmediaplayer.
for Media Player A and media player B,how can I get the data of playlist items again in playlistmediaplayer, because it may not get the data after adding the items.

**Comment by kahnivore** [comment]
Hi @z79422957 

Your code looks correct. Perhaps this is an execution order thing or perhaps your path is incorrect. Could you try using our Demo_MediaPlayer scene and setting the path via script to make sure that part is correct?

**Comment by z79422957** [comment]
Thanks for your reply.I tested that the path was right.
(1)I instantiate the prefab of playlistmediaplayer, mediaplayerA, mediaplayer B and displayugui first.
(2) then add the item data of playlistmediaplayer from streamingasset by c#.
The question is whether mediaplayerA and mediaplayerB can't get the item data of playlistmediaplayer.
What method should I call to get item data?

**Comment by kahnivore** [comment]
Are you adding the items to the playlist with _playlist.Playlist.Items.Add(items). I don't see it in the last screenshot you've posted.

**Comment by kahnivore** [comment]
Perhaps try turning the playlist off autoplay and then manually calling playlist.Play() once you're sure you've assigned the media players and added the items?

**Comment by z79422957** [comment]
item of playlist is added.
![image](https://user-images.githubusercontent.com/16982190/126130360-0af3045c-dc13-45db-a98f-9e3f34120b9b.png)
![image](https://user-images.githubusercontent.com/16982190/126130484-c9122742-0d34-4b18-971e-1fc48cb7934c.png)

**Comment by z79422957** [comment]
> Perhaps try turning the playlist off autoplay and then manually calling playlist.Play() once you're sure you've assigned the media players and added the items?

I tried, but I couldn't get the path.
![image](https://user-images.githubusercontent.com/16982190/126131940-42a26470-b36f-4fe0-affb-cc457857211b.png)
![image](https://user-images.githubusercontent.com/16982190/126132005-61885350-ff88-46d6-92f1-2a13d754f1f4.png)

**Comment by z79422957** [comment]
@kahnivore My project was 2.1.3 before,and There's nothing wrong with it.This issue occurred when upgrading to version 2.1.6, and is that relevant?

**Comment by z79422957** [comment]
When I finished adding item data, I tried to call Initialise() and OpenVideo() of MediaPlayer scripts before, but It doesn't solve the problem.

**Comment by kahnivore** [comment]
Strange, I've tested this on 2.1.6 and couldn't reproduce your problem. Perhaps you could send your project to unitysupport@renderheads.com? Is there anything else that changed when you upgraded to 2.1.6? I can't see any reason why upgrading to 2.1.6 would've broken the functionality.

**Comment by z79422957** [comment]
> Strange, I've tested this on 2.1.6 and couldn't reproduce your problem. Perhaps you could send your project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)? Is there anything else that changed when you upgraded to 2.1.6? I can't see any reason why upgrading to 2.1.6 would've broken the functionality.

The test package has been sent to your email.Thank you.

**Comment by kahnivore** [comment]
Hey @z79422957 

When I played your scene I got errors about AVPro DLL's not being found - are you getting those? It seems like the new version wasn't imported properly. To fix this, please restart Unity and then import the 2.1.6 package without doing anything else in the scene. 

Let us know if that fixes it?

**Comment by z79422957** [comment]
Fixed: AVPro DLL's not being found.
the Test1 file has been sent again,Thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 晚上10:37
***@***.***&gt;;
抄送:&nbsp;"James ***@***.******@***.***&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo] No media specified (#867)





 
Hey @z79422957
 
When I played your scene I got errors about AVPro DLL's not being found - are you getting those? It seems like the new version wasn't imported properly. To fix this, please restart Unity and then import the 2.1.6 package without doing anything else in the scene.
 
Let us know if that fixes it?

**Comment by kahnivore** [comment]
Hi there,

I had a look at your latest project but still getting AVPro DLL not found errors. When I re-import AVPro everything works as expected including the playlist. 

![image](https://user-images.githubusercontent.com/44468274/126472816-4ce12604-1093-4d03-9c50-ed4a3e982b40.png)

**Comment by z79422957** [comment]
There is no error in test1 file.Are you using the Test1 file?
&nbsp;https://drive.google.com/file/d/1ZZdM4XQkDFjaDDz1ToIP1XAe3kRbbeXB/view?usp=sharing









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 晚上6:14
***@***.***&gt;;
抄送:&nbsp;"James ***@***.******@***.***&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo] No media specified (#867)





 
Hi there,
 
I had a look at your latest project but still getting AVPro DLL not found errors. When I re-import AVPro everything works as expected including the playlist.

**Comment by AndrewRH** [comment]
Hi @z79422957 

Try adding this code to PlaylistMediaPlayer.cs line 578:

```
				else if (_playlistAutoProgress && _currentItem == null)
				{
					JumpToItem(_playlistIndex);
				}
```

![image](https://user-images.githubusercontent.com/5418126/126662509-668b990d-9ecc-41db-b21e-b4639700d643.png)

Does that fix the problem?

Thanks,

**Comment by z79422957** [comment]
> Hi @z79422957
> 
> Try adding this code to PlaylistMediaPlayer.cs line 578:
> 
> ```
> 				else if (_playlistAutoProgress && _currentItem == null)
> 				{
> 					JumpToItem(_playlistIndex);
> 				}
> ```
> 
> ![image](https://user-images.githubusercontent.com/5418126/126662509-668b990d-9ecc-41db-b21e-b4639700d643.png)
> 
> Does that fix the problem?
> 
> Thanks,

Thank you for your reply. you solved this issue! But it always plays automatically.If I set autoplay item of playlistmediaplayer and auto play of mediaplayerA/B to false, so it is also played automatically. My project has not been played automatically before.What should I do?

**Comment by AndrewRH** [comment]
Add this:

`mediaItem.startMode = PlaylistMediaPlayer.StartMode.Manual;`

Thanks,

**Comment by z79422957** [comment]
OK, It won't play automatically anymore.Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 晚上6:35
***@***.***&gt;;
抄送:&nbsp;"James ***@***.******@***.***&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo] PlaylistMediaPlayer not playing media via scripted correctly (#867)





 
Add this:
 
mediaItem.startMode = PlaylistMediaPlayer.StartMode.Manual;
 
Thanks,

**Comment by z79422957** [comment]
Sorry, the problem still hasn't been solved. I have 6 items in total. Now, after changing to manual, all items need to be played manually.


I want the entire playlist media player not to play automatically at the beginning.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 晚上6:35
***@***.***&gt;;
抄送:&nbsp;"James ***@***.******@***.***&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo] PlaylistMediaPlayer not playing media via scripted correctly (#867)





 
Add this:
 
mediaItem.startMode = PlaylistMediaPlayer.StartMode.Manual;
 
Thanks,

**Comment by AndrewRH** [comment]
> Sorry, the problem still hasn't been solved. I have 6 items in total. Now, after changing to manual, all items need to be played manually. I want the entire playlist media player not to play automatically at the beginning.

Oh I see.  Okay let me look into it and get back to you.

**Comment by z79422957** [comment]
There are two bugs now, the test file has been sent to the mailbox.
View this scene file: assets - scenes - Bug2021.7.24.unity:
(1)Click Run and then stop running, the path of MediaplayerA and MediaplayerB may be wrong.Click Run again and it will play the second item. It will not play from the first item.
(2) All of the buttons event below are invalid and confusing.

**Comment by z79422957** [comment]
> > Hi @z79422957
> > Try adding this code to PlaylistMediaPlayer.cs line 578:
> > ```
> > 				else if (_playlistAutoProgress && _currentItem == null)
> > 				{
> > 					JumpToItem(_playlistIndex);
> > 				}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/5418126/126662509-668b990d-9ecc-41db-b21e-b4639700d643.png)
> > Does that fix the problem?
> > Thanks,
> 
> Thank you for your reply. you solved this issue! But it always plays automatically.If I set autoplay item of playlistmediaplayer and auto play of mediaplayerA/B to false, so it is also played automatically. My project has not been played automatically before.What should I do?

In new AVpro version 2.1.7, you added this code to PlaylistMediaPlayer.cs line 531:
{
	if (!Application.isPlaying) return;
}
I can solve this problem with 2.1.7, right?

**Comment by AndrewRH** [comment]
Please upgrade to version 2.1.8 (to be released very soon) as I believe we have solved most of these problems there.

The documentation for PlaylistMediaPlayer has also been upgraded:
https://www.renderheads.com/content/docs/AVProVideo/articles/component-playlist-media-player.html

I am closing this issue.  If you're still having problems with 2.1.8 please create a new issue thread.

Thanks,

**Comment by z79422957** [comment]
OK, Thank you.
