### ISSUE TITLE
Switch Stereo Top-Bottom order?

### ISSUE THREAD

**Issue by mbzworld** [RenderHeads/UnityPlugin-AVProVideo#934]
AVPro 1.9.12 (Unity 2019.4.3f1)

I have a Unity project where there is a 360 Sphere (insideStereo TopBottom) and a curved screen (Opaque Stereo TopBottom)

The sphere video is playing alright, however, the curved screen video is showing stereo reversed. To make sure that was the issue, I actually edited the video where I switched top/bottom video and it worked. 

Is there a quick fix for this like changing the shader or something?

Thanks!

**Comment by mbzworld** [comment]
This reversed issue is happening on a Canvas that has Display uGUI added to it. I even tried the demo scene (Video Controls), changed video packing to TopBottom and added UpdateStereoMaterial script to it and the same issue occurred; reversed eyes.

**Comment by AndrewRH** [comment]
1.9.12 is very old version and I suspect this issue was fixed.

Please upgrade to the latest version of 1.x which is 1.11.7

Thanks,

**Comment by mbzworld** [comment]
I just updated to the latest 1.x version and unfortunately, the issue persisted. 

This issue is happening on Windows 10 x64. The build is not intended for any other platform. 

Is there a quick fix possible via modding the shader?

**Comment by AndrewRH** [comment]
Hmm do you know which shaders are being used?

I guess it's "AVProVideo/VR/InsideSphere Unlit (stereo+fog)"
and
"AVProVideo/UI/Stereo"
?

I looked through the shaders but couldn't see any problem - they both use the same logic to determine stereo offsets.

Perhaps you could also enable the "Debug Eye Tint" option in the "Visual" section of the MediaPlayer component to really confirm that the red-green is swapped on your InsideSphere vs Canvas?

A screenshot would be nice as well.

Thanks,

**Comment by mbzworld** [comment]
I appreciate your response.

The shader in use for the sphere is: 
AVProVideo/VR/InsideSphere Unlit (stereo+fog) (as you mentioned)
Screenshot:
https://i.imgur.com/1VJL12H.png

And on the rectangular screen (Display uGUI), the shader is:
AVProVideo/Unlit/Opaque (texture+color+fog+stereo support)
Screenshot:
https://i.imgur.com/mnik4ad.png

I tried the Debug Eye Tint and the left eye was green, the right was red. So it seems that AVPro is correctly sending the image to the VR headset, but maybe reading it in reverse to begin with?

**Comment by kahnivore** [comment]
Which headset are you using?

**Comment by mbzworld** [comment]
I am using Oculus Quest 2 w/link

This issue occurred prior to using the curved UI.

**Comment by AndrewRH** [comment]
Why are you assigning a material to the DisplayUGUI component?

It shouldn't require any material and that may complicate things - could you try without any material assigned please?

Thanks,

**Comment by mbzworld** [comment]
I just tried removing the material from the DisplayUGUI and it didn't fix
the problem.
Anyways, in runtime, it seems that another material is being assigned to it
anyways:
https://i.imgur.com/5ySE6nW.png

Best Regards
Muhammad Bayazid
Co-Founder/CEO
LightArt Productions / Light Art VR
Office: +1-917-508-7859
Mobile: +1-708-271-3815

E-mail: ***@***.***
            ***@***.***

Websites: www.lightartproductions.com
                 www.lightartvr.com


Please note that the information transmitted is intended only for the
person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review, re-transmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. if you
received this in error, please contact the sender and delete the material
from any computer.
