### ISSUE TITLE
TestFlight builds report incorrect plugin version

### ISSUE THREAD

**Issue by ghost** [RenderHeads/UnityPlugin-AVProVideo#973]
**Describe the issue**
Error of mismatching plugin version number keeps getting displayed, when using TestFlight. Testing a build when building to the device straight for XCode doesn't display the error, when then archiving and uploading to TestFlight, the error is observed after downloading.

Im having issues playing videos, and I'm trying to determine if this error is one of the causes.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.20
 - AVPro Video version: 2.2.2
 - Operating system version: iOS 15.0.2 and iOS 14.8 
 - Device model: iPhone XR, iPhone 11
 - Video specs (resolution, frame-rate, codec, file size): displayed on app launch, there is no video loaded.

**To Reproduce**
1. Build an iOS XCode project with AVPRo 2.2.2 - with no active media player
2. Build from XCode to device -> observe everything is ok
3. Archive the build and upload to TestFlight
4. Once downloaded onto a device, launch
5. Observe error

**Logs**
[AVProVideo] Plugin version number 1.0.0-ultra build 4 doesn't match the expected version number 2.2.2.  It looks like the plugin didn't upgrade correctly.  To resolve this please restart Unity and try to upgrade the package again.

**Note**
I first started getting this issue after updating to 2.2.2, by importing the new version into the project with the previous version still present. I then remove AVPro from the project (by just deleting /Assets/AVPro) and imported the 2.2.2 "fresh".

I also deleted the XCode project and created a new fresh one, not replace/ appended when building.

**Comment by MorrisRH** [comment]
Turns out this is the result of a new feature in Xcode.
Please see [here](https://developer.apple.com/forums/thread/690647) for more information about what's happening and how to disable it.

**Comment by tomkail** [comment]
Hi! We just encountered this. The fix is to disable automatic XCode app versioning, which we don't want to do because we rely on it. Can this not be fixed in AVProVideo?

**Comment by MorrisRH** [comment]
Commenting out the check is probably the best for now.
We'll see what can be done but changing how we handle versioning in the plug-in (much like for yourselves) is not a quick thing to do.

**Comment by MorrisRH** [comment]
This issue has been fixed and will make it into the next release.

I've changed the plugin to no longer use the bundle version string so if it is modified by some aspect of the build process in the future it will no longer display the warning message.

**Comment by Chris-RH** [comment]
The latest version has been released.  Please let us know if your issue has not been fixed.

**Comment by pnkjstha** [comment]
I have updated to latest AvProVideo version but the issue is still shown after installing from TestFlight app.

**Comment by pnkjstha** [comment]
[AVProVideo] Plugin version number 2.7.1-trial build 1606 doesn't match the expected version number 2.7.3.  It looks like the plugin didn't upgrade correctly.  To resolve this please restart Unity and try to upgrade the package again.

This is shown in console. But AvproVideo package is already updated to version 2.8.4.
